import { IUser } from "@/types/users";

export const users: IUser[] = [
  {
    avatar: "/avatars/david-nguyen.jpg",
    name: "Mr. David Nguyen",
    id: "LOO0001",
    phone: "(322) 243-3452",
    email: "david.nguyen@gmail.com",
    type: "Loan Officer",
    experience: "5 years",
    status: "ACTIVE",
  },
  {
    avatar: "/avatars/jennie-pink.jpg",
    name: "Ms. Jennie Pink",
    id: "UW00001",
    phone: "(322) 243-3452",
    email: "jenniepink@gmail.com",
    type: "Underwriter",
    experience: "5 years",
    status: "ACTIVE",
  },
  {
    avatar: "/avatars/pep-guardiola.jpg",
    name: "Mr. Pep Guardiola",
    id: "LP00001",
    phone: "(322) 243-3452",
    email: "pepguardiola@gmail.com",
    type: "Loan Processor",
    experience: "5 years",
    status: "ACTIVE",
  },
  {
    avatar: "/avatars/bruno-mar.jpg",
    name: "Mr. Bruno Mar",
    id: "AD00001",
    phone: "(322) 243-3452",
    email: "brunomors@gmail.com",
    type: "Admin",
    experience: "5 years",
    status: "ACTIVE",
  },
  {
    avatar: "/avatars/david-beckham.jpg",
    name: "Mr. David Beckham",
    id: "ME00001",
    phone: "(322) 243-3452",
    email: "davidbeckham@gmail.com",
    type: "Member",
    experience: "5 years",
    status: "ACTIVE",
  },
];