export const customerData = [
  {
    id: 1,
    CustomerId: "C001",
    FirstName: "John",
    LastName: "Doe",
    Company: "ABC Corp",
    City: "Hà Nội",
    Country: "Việt Nam",
    Phone1: "0123456789",
    Phone2: "0987654321",
    Email: "john.doe@example.com",
    SubscriptionDate: "2024-01-01",
    Website: "https://abc.com"
  },
  {
    id: 2,
    CustomerId: "C002",
    FirstName: "Jane",
    LastName: "Smith",
    Company: "XYZ Ltd",
    City: "Hồ Chí Minh",
    Country: "Việt Nam",
    Phone1: "0912345678",
    Phone2: "0938765432",
    Email: "jane.smith@example.com",
    SubscriptionDate: "2024-02-15",
    Website: "https://xyz.vn"
  },
  {
    id: 3,
    CustomerId: "C003",
    FirstName: "Minh",
    LastName: "Nguyen",
    Company: "MinhTech",
    City: "Đà Nẵng",
    Country: "Việt Nam",
    Phone1: "0901122334",
    Phone2: "",
    Email: "minh.nguyen@minhtech.com",
    SubscriptionDate: "2023-12-10",
    Website: "https://minhtech.com"
  },
  {
    id: 4,
    CustomerId: "C004",
    FirstName: "Linh",
    LastName: "Tran",
    Company: "Linh Solutions",
    City: "Cần Thơ",
    Country: "Việt Nam",
    Phone1: "0977888999",
    Phone2: "",
    Email: "linh.tran@linhsolutions.vn",
    SubscriptionDate: "2024-03-20",
    Website: "https://linhsolutions.vn"
  },
  {
    id: 5,
    CustomerId: "C005",
    FirstName: "David",
    LastName: "Pham",
    Company: "DP Tech",
    City: "Hải Phòng",
    Country: "Việt Nam",
    Phone1: "0966123456",
    Phone2: "0911223344",
    Email: "david.pham@dptech.com",
    SubscriptionDate: "2024-04-05",
    Website: "https://dptech.com"
  },
  {
    id: 6,
    CustomerId: "C006",
    FirstName: "Mai",
    LastName: "Le",
    Company: "MaiLe Group",
    City: "Nha Trang",
    Country: "Việt Nam",
    Phone1: "0988111222",
    Phone2: "",
    Email: "mai.le@mailegroup.vn",
    SubscriptionDate: "2024-05-10",
    Website: "https://mailegroup.vn"
  },
  {
    id: 7,
    CustomerId: "C007",
    FirstName: "Huy",
    LastName: "Nguyen",
    Company: "HuyMedia",
    City: "Huế",
    Country: "Việt Nam",
    Phone1: "0911000007",
    Phone2: "",
    Email: "huy.nguyen@huymedia.vn",
    SubscriptionDate: "2024-05-15",
    Website: "https://huymedia.vn"
  },
  {
    id: 8,
    CustomerId: "C008",
    FirstName: "Quang",
    LastName: "Le",
    Company: "QuangSoft",
    City: "Vũng Tàu",
    Country: "Việt Nam",
    Phone1: "0911000008",
    Phone2: "",
    Email: "quang.le@quangsoft.com",
    SubscriptionDate: "2024-05-16",
    Website: "https://quangsoft.com"
  },
  {
    id: 9,
    CustomerId: "C009",
    FirstName: "Hoa",
    LastName: "Pham",
    Company: "HoaDecor",
    City: "Bắc Ninh",
    Country: "Việt Nam",
    Phone1: "0911000009",
    Phone2: "",
    Email: "hoa.pham@hoadecor.vn",
    SubscriptionDate: "2024-05-17",
    Website: "https://hoadecor.vn"
  },
  {
    id: 10,
    CustomerId: "C010",
    FirstName: "Tuan",
    LastName: "Tran",
    Company: "TuanAuto",
    City: "Biên Hòa",
    Country: "Việt Nam",
    Phone1: "0911000010",
    Phone2: "",
    Email: "tuan.tran@tuanauto.vn",
    SubscriptionDate: "2024-05-18",
    Website: "https://tuanauto.vn"
  },
  {
    id: 11,
    CustomerId: "C011",
    FirstName: "Khanh",
    LastName: "Vo",
    Company: "KhanhFoods",
    City: "Long An",
    Country: "Việt Nam",
    Phone1: "0911000011",
    Phone2: "",
    Email: "khanh.vo@khanhfoods.vn",
    SubscriptionDate: "2024-05-19",
    Website: "https://khanhfoods.vn"
  },
  {
    id: 12,
    CustomerId: "C012",
    FirstName: "Phuc",
    LastName: "Nguyen",
    Company: "PhucTravel",
    City: "Quảng Ninh",
    Country: "Việt Nam",
    Phone1: "0911000012",
    Phone2: "",
    Email: "phuc.nguyen@phuctravel.vn",
    SubscriptionDate: "2024-05-20",
    Website: "https://phuctravel.vn"
  },
  {
    id: 13,
    CustomerId: "C013",
    FirstName: "Son",
    LastName: "Le",
    Company: "SonMobile",
    City: "Nam Định",
    Country: "Việt Nam",
    Phone1: "0911000013",
    Phone2: "",
    Email: "son.le@sonmobile.vn",
    SubscriptionDate: "2024-05-21",
    Website: "https://sonmobile.vn"
  },
  {
    id: 14,
    CustomerId: "C014",
    FirstName: "Lan",
    LastName: "Pham",
    Company: "LanSpa",
    City: "Vĩnh Long",
    Country: "Việt Nam",
    Phone1: "0911000014",
    Phone2: "",
    Email: "lan.pham@lanspa.vn",
    SubscriptionDate: "2024-05-22",
    Website: "https://lanspa.vn"
  },
  {
    id: 15,
    CustomerId: "C015",
    FirstName: "Hung",
    LastName: "Tran",
    Company: "HungTech",
    City: "Thái Nguyên",
    Country: "Việt Nam",
    Phone1: "0911000015",
    Phone2: "",
    Email: "hung.tran@hungtech.vn",
    SubscriptionDate: "2024-05-23",
    Website: "https://hungtech.vn"
  },
  {
    id: 16,
    CustomerId: "C016",
    FirstName: "Thu",
    LastName: "Nguyen",
    Company: "ThuDesign",
    City: "Bình Dương",
    Country: "Việt Nam",
    Phone1: "0911000016",
    Phone2: "",
    Email: "thu.nguyen@thudesign.vn",
    SubscriptionDate: "2024-05-24",
    Website: "https://thudesign.vn"
  },
  {
    id: 17,
    CustomerId: "C017",
    FirstName: "Duc",
    LastName: "Pham",
    Company: "DucAuto",
    City: "Bình Định",
    Country: "Việt Nam",
    Phone1: "0911000017",
    Phone2: "",
    Email: "duc.pham@ducauto.vn",
    SubscriptionDate: "2024-05-25",
    Website: "https://ducauto.vn"
  },
  {
    id: 18,
    CustomerId: "C018",
    FirstName: "Hanh",
    LastName: "Le",
    Company: "HanhFoods",
    City: "Phú Yên",
    Country: "Việt Nam",
    Phone1: "0911000018",
    Phone2: "",
    Email: "hanh.le@hanhfoods.vn",
    SubscriptionDate: "2024-05-26",
    Website: "https://hanhfoods.vn"
  },
  {
    id: 19,
    CustomerId: "C019",
    FirstName: "Bao",
    LastName: "Nguyen",
    Company: "BaoDecor",
    City: "Quảng Nam",
    Country: "Việt Nam",
    Phone1: "0911000019",
    Phone2: "",
    Email: "bao.nguyen@baodecor.vn",
    SubscriptionDate: "2024-05-27",
    Website: "https://baodecor.vn"
  },
  {
    id: 20,
    CustomerId: "C020",
    FirstName: "Tam",
    LastName: "Tran",
    Company: "TamTravel",
    City: "Bến Tre",
    Country: "Việt Nam",
    Phone1: "0911000020",
    Phone2: "",
    Email: "tam.tran@tamtravel.vn",
    SubscriptionDate: "2024-05-28",
    Website: "https://tamtravel.vn"
  },
  {
    id: 21,
    CustomerId: "C021",
    FirstName: "Vy",
    LastName: "Le",
    Company: "VySpa",
    City: "Sóc Trăng",
    Country: "Việt Nam",
    Phone1: "0911000021",
    Phone2: "",
    Email: "vy.le@vyspa.vn",
    SubscriptionDate: "2024-05-29",
    Website: "https://vyspa.vn"
  },
  {
    id: 22,
    CustomerId: "C022",
    FirstName: "Phat",
    LastName: "Nguyen",
    Company: "PhatMobile",
    City: "Bạc Liêu",
    Country: "Việt Nam",
    Phone1: "0911000022",
    Phone2: "",
    Email: "phat.nguyen@phatmobile.vn",
    SubscriptionDate: "2024-05-30",
    Website: "https://phatmobile.vn"
  },
  {
    id: 23,
    CustomerId: "C023",
    FirstName: "Kieu",
    LastName: "Pham",
    Company: "KieuDesign",
    City: "Trà Vinh",
    Country: "Việt Nam",
    Phone1: "0911000023",
    Phone2: "",
    Email: "kieu.pham@kieudesign.vn",
    SubscriptionDate: "2024-06-01",
    Website: "https://kieudesign.vn"
  },
  {
    id: 24,
    CustomerId: "C024",
    FirstName: "Tung",
    LastName: "Tran",
    Company: "TungAuto",
    City: "Hậu Giang",
    Country: "Việt Nam",
    Phone1: "0911000024",
    Phone2: "",
    Email: "tung.tran@tungauto.vn",
    SubscriptionDate: "2024-06-02",
    Website: "https://tungauto.vn"
  },
  {
    id: 25,
    CustomerId: "C025",
    FirstName: "Dao",
    LastName: "Le",
    Company: "DaoFoods",
    City: "An Giang",
    Country: "Việt Nam",
    Phone1: "0911000025",
    Phone2: "",
    Email: "dao.le@daofoods.vn",
    SubscriptionDate: "2024-06-03",
    Website: "https://daofoods.vn"
  },
  {
    id: 26,
    CustomerId: "C026",
    FirstName: "Quyen",
    LastName: "Nguyen",
    Company: "QuyenDecor",
    City: "Kiên Giang",
    Country: "Việt Nam",
    Phone1: "0911000026",
    Phone2: "",
    Email: "quyen.nguyen@quyendecor.vn",
    SubscriptionDate: "2024-06-04",
    Website: "https://quyendecor.vn"
  },
  {
    id: 27,
    CustomerId: "C027",
    FirstName: "Hieu",
    LastName: "Pham",
    Company: "HieuTech",
    City: "Tây Ninh",
    Country: "Việt Nam",
    Phone1: "0911000027",
    Phone2: "",
    Email: "hieu.pham@hieutech.vn",
    SubscriptionDate: "2024-06-05",
    Website: "https://hieutech.vn"
  },
  {
    id: 28,
    CustomerId: "C028",
    FirstName: "Trang",
    LastName: "Tran",
    Company: "TrangSpa",
    City: "Bình Thuận",
    Country: "Việt Nam",
    Phone1: "0911000028",
    Phone2: "",
    Email: "trang.tran@trangspa.vn",
    SubscriptionDate: "2024-06-06",
    Website: "https://trangspa.vn"
  },
  {
    id: 29,
    CustomerId: "C029",
    FirstName: "Nam",
    LastName: "Le",
    Company: "NamMobile",
    City: "Ninh Thuận",
    Country: "Việt Nam",
    Phone1: "0911000029",
    Phone2: "",
    Email: "nam.le@nammobile.vn",
    SubscriptionDate: "2024-06-07",
    Website: "https://nammobile.vn"
  },
  {
    id: 30,
    CustomerId: "C030",
    FirstName: "Yen",
    LastName: "Nguyen",
    Company: "YenFoods",
    City: "Kon Tum",
    Country: "Việt Nam",
    Phone1: "0911000030",
    Phone2: "",
    Email: "yen.nguyen@yenfoods.vn",
    SubscriptionDate: "2024-06-08",
    Website: "https://yenfoods.vn"
  },
  {
    id: 31,
    CustomerId: "C031",
    FirstName: "Phuong",
    LastName: "Pham",
    Company: "PhuongDesign",
    City: "Gia Lai",
    Country: "Việt Nam",
    Phone1: "0911000031",
    Phone2: "",
    Email: "phuong.pham@phuongdesign.vn",
    SubscriptionDate: "2024-06-09",
    Website: "https://phuongdesign.vn"
  },
  {
    id: 32,
    CustomerId: "C032",
    FirstName: "Tiep",
    LastName: "Tran",
    Company: "TiepAuto",
    City: "Đắk Lắk",
    Country: "Việt Nam",
    Phone1: "0911000032",
    Phone2: "",
    Email: "tiep.tran@tiepauto.vn",
    SubscriptionDate: "2024-06-10",
    Website: "https://tiepauto.vn"
  },
  {
    id: 33,
    CustomerId: "C033",
    FirstName: "Luan",
    LastName: "Le",
    Company: "LuanFoods",
    City: "Đắk Nông",
    Country: "Việt Nam",
    Phone1: "0911000033",
    Phone2: "",
    Email: "luan.le@luanfoods.vn",
    SubscriptionDate: "2024-06-11",
    Website: "https://luanfoods.vn"
  },
  {
    id: 34,
    CustomerId: "C034",
    FirstName: "Binh",
    LastName: "Nguyen",
    Company: "BinhDecor",
    City: "Lâm Đồng",
    Country: "Việt Nam",
    Phone1: "0911000034",
    Phone2: "",
    Email: "binh.nguyen@binhdecor.vn",
    SubscriptionDate: "2024-06-12",
    Website: "https://binhdecor.vn"
  },
  {
    id: 35,
    CustomerId: "C035",
    FirstName: "Tuyet",
    LastName: "Pham",
    Company: "TuyetSpa",
    City: "Cà Mau",
    Country: "Việt Nam",
    Phone1: "0911000035",
    Phone2: "",
    Email: "tuyet.pham@tuyetspa.vn",
    SubscriptionDate: "2024-06-13",
    Website: "https://tuyetspa.vn"
  },
  {
    id: 36,
    CustomerId: "C036",
    FirstName: "Viet",
    LastName: "Tran",
    Company: "VietTech",
    City: "Điện Biên",
    Country: "Việt Nam",
    Phone1: "0911000036",
    Phone2: "",
    Email: "viet.tran@viettech.vn",
    SubscriptionDate: "2024-06-14",
    Website: "https://viettech.vn"
  },
  {
    id: 37,
    CustomerId: "C037",
    FirstName: "Hao",
    LastName: "Le",
    Company: "HaoFoods",
    City: "Lai Châu",
    Country: "Việt Nam",
    Phone1: "0911000037",
    Phone2: "",
    Email: "hao.le@haofoods.vn",
    SubscriptionDate: "2024-06-15",
    Website: "https://haofoods.vn"
  },
  {
    id: 38,
    CustomerId: "C038",
    FirstName: "My",
    LastName: "Nguyen",
    Company: "MyDecor",
    City: "Sơn La",
    Country: "Việt Nam",
    Phone1: "0911000038",
    Phone2: "",
    Email: "my.nguyen@mydecor.vn",
    SubscriptionDate: "2024-06-16",
    Website: "https://mydecor.vn"
  },
  {
    id: 39,
    CustomerId: "C039",
    FirstName: "Hien",
    LastName: "Pham",
    Company: "HienDesign",
    City: "Yên Bái",
    Country: "Việt Nam",
    Phone1: "0911000039",
    Phone2: "",
    Email: "hien.pham@hiendesign.vn",
    SubscriptionDate: "2024-06-17",
    Website: "https://hiendesign.vn"
  },
  {
    id: 40,
    CustomerId: "C040",
    FirstName: "Loi",
    LastName: "Tran",
    Company: "LoiAuto",
    City: "Tuyên Quang",
    Country: "Việt Nam",
    Phone1: "0911000040",
    Phone2: "",
    Email: "loi.tran@loiauto.vn",
    SubscriptionDate: "2024-06-18",
    Website: "https://loiauto.vn"
  },
  {
    id: 41,
    CustomerId: "C041",
    FirstName: "Phuoc",
    LastName: "Le",
    Company: "PhuocFoods",
    City: "Hà Giang",
    Country: "Việt Nam",
    Phone1: "0911000041",
    Phone2: "",
    Email: "phuoc.le@phuocfoods.vn",
    SubscriptionDate: "2024-06-19",
    Website: "https://phuocfoods.vn"
  },
  {
    id: 42,
    CustomerId: "C042",
    FirstName: "Loan",
    LastName: "Nguyen",
    Company: "LoanDecor",
    City: "Bắc Kạn",
    Country: "Việt Nam",
    Phone1: "0911000042",
    Phone2: "",
    Email: "loan.nguyen@loandecor.vn",
    SubscriptionDate: "2024-06-20",
    Website: "https://loandecor.vn"
  },
  {
    id: 43,
    CustomerId: "C043",
    FirstName: "Nghia",
    LastName: "Pham",
    Company: "NghiaTech",
    City: "Cao Bằng",
    Country: "Việt Nam",
    Phone1: "0911000043",
    Phone2: "",
    Email: "nghia.pham@nghiatech.vn",
    SubscriptionDate: "2024-06-21",
    Website: "https://nghiatech.vn"
  },
  {
    id: 44,
    CustomerId: "C044",
    FirstName: "Thao",
    LastName: "Tran",
    Company: "ThaoSpa",
    City: "Lạng Sơn",
    Country: "Việt Nam",
    Phone1: "0911000044",
    Phone2: "",
    Email: "thao.tran@thaospa.vn",
    SubscriptionDate: "2024-06-22",
    Website: "https://thaospa.vn"
  },
  {
    id: 45,
    CustomerId: "C045",
    FirstName: "Hieu",
    LastName: "Le",
    Company: "HieuFoods",
    City: "Hòa Bình",
    Country: "Việt Nam",
    Phone1: "0911000045",
    Phone2: "",
    Email: "hieu.le@hieufoods.vn",
    SubscriptionDate: "2024-06-23",
    Website: "https://hieufoods.vn"
  },
  {
    id: 46,
    CustomerId: "C046",
    FirstName: "Dung",
    LastName: "Nguyen",
    Company: "DungDecor",
    City: "Phú Thọ",
    Country: "Việt Nam",
    Phone1: "0911000046",
    Phone2: "",
    Email: "dung.nguyen@dungdecor.vn",
    SubscriptionDate: "2024-06-24",
    Website: "https://dungdecor.vn"
  },
  {
    id: 47,
    CustomerId: "C047",
    FirstName: "Tuan",
    LastName: "Pham",
    Company: "TuanDesign",
    City: "Hà Nam",
    Country: "Việt Nam",
    Phone1: "0911000047",
    Phone2: "",
    Email: "tuan.pham@tuandesign.vn",
    SubscriptionDate: "2024-06-25",
    Website: "https://tuandesign.vn"
  },
  {
    id: 48,
    CustomerId: "C048",
    FirstName: "Linh",
    LastName: "Tran",
    Company: "LinhAuto",
    City: "Nam Định",
    Country: "Việt Nam",
    Phone1: "0911000048",
    Phone2: "",
    Email: "linh.tran@linhauto.vn",
    SubscriptionDate: "2024-06-26",
    Website: "https://linhauto.vn"
  },
  {
    id: 49,
    CustomerId: "C049",
    FirstName: "Quoc",
    LastName: "Le",
    Company: "QuocFoods",
    City: "Ninh Bình",
    Country: "Việt Nam",
    Phone1: "0911000049",
    Phone2: "",
    Email: "quoc.le@quocfoods.vn",
    SubscriptionDate: "2024-06-27",
    Website: "https://quocfoods.vn"
  },
  {
    id: 50,
    CustomerId: "C050",
    FirstName: "Bao",
    LastName: "Nguyen",
    Company: "BaoTech",
    City: "Thanh Hóa",
    Country: "Việt Nam",
    Phone1: "0911000050",
    Phone2: "",
    Email: "bao.nguyen@baotech.vn",
    SubscriptionDate: "2024-06-28",
    Website: "https://baotech.vn"
  }
];